language: "ruby"

rvm:
  - "2.0"
  - "2.3.3"
  - "2.4.0"

sudo: false

install:
  - bundle install --retry=3

addons:
  code_climate:
    repo_token: cad4913c49d614008c332cda660cf909de208e335201aa8bfab373b9740e85be

after_success:
  - bundle exec codeclimate-test-reporter
